/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DataRouteImport } from './routes/data'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as ModularRouteImport } from './routes/modular'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as SchachRouteImport } from './routes/schach'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as AuthenticatedAdminPricesRouteImport } from './routes/_authenticated/admin/prices'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ModularRoute = ModularRouteImport.update({
  id: '/modular',
  path: '/modular',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const SchachRoute = SchachRouteImport.update({
  id: '/schach',
  path: '/schach',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPricesRoute =
  AuthenticatedAdminPricesRouteImport.update({
    id: '/admin/prices',
    path: '/admin/prices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data': typeof DataRoute
  '/extension': typeof ExtensionRoute
  '/lookup': typeof LookupRoute
  '/modular': typeof ModularRoute
  '/quotes': typeof QuotesRoute
  '/schach': typeof SchachRoute
  '/unlock': typeof UnlockRoute
  '/admin/prices': typeof AuthenticatedAdminPricesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data': typeof DataRoute
  '/extension': typeof ExtensionRoute
  '/lookup': typeof LookupRoute
  '/modular': typeof ModularRoute
  '/quotes': typeof QuotesRoute
  '/schach': typeof SchachRoute
  '/unlock': typeof UnlockRoute
  '/admin/prices': typeof AuthenticatedAdminPricesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/data': typeof DataRoute
  '/extension': typeof ExtensionRoute
  '/lookup': typeof LookupRoute
  '/modular': typeof ModularRoute
  '/quotes': typeof QuotesRoute
  '/schach': typeof SchachRoute
  '/unlock': typeof UnlockRoute
  '/_authenticated/admin/prices': typeof AuthenticatedAdminPricesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/data'
    | '/extension'
    | '/lookup'
    | '/modular'
    | '/quotes'
    | '/schach'
    | '/unlock'
    | '/admin/prices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/data'
    | '/extension'
    | '/lookup'
    | '/modular'
    | '/quotes'
    | '/schach'
    | '/unlock'
    | '/admin/prices'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/data'
    | '/extension'
    | '/lookup'
    | '/modular'
    | '/quotes'
    | '/schach'
    | '/unlock'
    | '/_authenticated/admin/prices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DataRoute: typeof DataRoute
  ExtensionRoute: typeof ExtensionRoute
  LookupRoute: typeof LookupRoute
  ModularRoute: typeof ModularRoute
  QuotesRoute: typeof QuotesRoute
  SchachRoute: typeof SchachRoute
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modular': {
      id: '/modular'
      path: '/modular'
      fullPath: '/modular'
      preLoaderRoute: typeof ModularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schach': {
      id: '/schach'
      path: '/schach'
      fullPath: '/schach'
      preLoaderRoute: typeof SchachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/prices': {
      id: '/_authenticated/admin/prices'
      path: '/admin/prices'
      fullPath: '/admin/prices'
      preLoaderRoute: typeof AuthenticatedAdminPricesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminPricesRoute: typeof AuthenticatedAdminPricesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminPricesRoute: AuthenticatedAdminPricesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DataRoute: DataRoute,
  ExtensionRoute: ExtensionRoute,
  LookupRoute: LookupRoute,
  ModularRoute: ModularRoute,
  QuotesRoute: QuotesRoute,
  SchachRoute: SchachRoute,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
